And error occurred when Install and Build Here are the errors
$ tsc --emitDeclarationOnly
node_modules/@material-ui/types/index.d.ts(26,54): error TS2694: Namespace 'React' has no exported member 'ComponentProps'.
node_modules/@material-ui/types/index.d.ts(30,46): error TS2694: Namespace 'React' has no exported member 'ComponentProps'.
node_modules/@types/hoist-non-react-statics/index.d.ts(59,29): error TS2694: Namespace 'React' has no exported member 'MemoExoticComponent'.
node_modules/@types/hoist-non-react-statics/index.d.ts(61,35): error TS2694: Namespace 'React' has no exported member 'ForwardRefExoticComponent'.
node_modules/@types/react-dom/index.d.ts(21,43): error TS2305: Module '"react"' has no exported member 'ReactPortal'.
node_modules/@types/react-dom/index.d.ts(94,18): error TS2314: Generic type 'ReactElement<P>' requires 1 type argument(s).
node_modules/@types/react-dom/test-utils/index.d.ts(70,31): error TS2314: Generic type 'ReactElement<P>' requires 1 type argument(s).
node_modules/@types/react-dom/test-utils/index.d.ts(74,21): error TS2314: Generic type 'ReactElement<P>' requires 1 type argument(s).
node_modules/@types/react-dom/test-utils/index.d.ts(186,14): error TS2314: Generic type 'ReactElement<P>' requires 1 type argument(s).
node_modules/@types/react-dom/test-utils/index.d.ts(191,14): error TS2314: Generic type 'ReactElement<P>' requires 1 type argument(s).
node_modules/@types/react-dom/test-utils/index.d.ts(196,14): error TS2314: Generic type 'ReactElement<P>' requires 1 type argument(s).
node_modules/@types/react-dom/test-utils/index.d.ts(201,14): error TS2314: Generic type 'ReactElement<P>' requires 1 type argument(s).